Sources/MyBlog/Models/LayoutViewModel.cs
using MyBlog.Engine;
using MyBlog.Engine.Data.Models;
using MyBlog.Strings;
using MyLib.Web;
using MyLib.Web.Helpers;
using System;

namespace MyBlog.Models
{
    public sealed class LayoutViewModel
    {
        #region Declarations

        private static readonly string _version;

        #endregion

        #region Constructor

        /// <summary>
        /// Static constructor
        /// </summary>
        static LayoutViewModel()
        {
            _version = ApplicationHelper.GetVersion() + " " + Resources.VersionSuffix;
        }

        /// <summary>
        /// Constructor
        /// </summary>
        private LayoutViewModel()
        {
            using (var db = new DataService())
            {
                Categories = db.GetGateoriesCounters();
                Archives = db.GetArchives();
                User = UserService.Get(db);
                UserSettings = UserSettingsService.Get();
            }
        }

        #endregion

        #region Properties

        /// <summary>
        ///  counters
        /// </summary>
        public Counter[] Categories { get; }

        /// <summary>
        /// Archives
        /// </summary>
        public ArchiveLink[] Archives { get; }

        /// <summary>
        /// Version
        /// </summary>
        public String Version => _version;

        /// <summary>
        /// User loged in
        /// </summary>
        public UserProfile User { get; }

        /// <summary>
        /// User's settings
        /// </summary>
        public UserSettings UserSettings { get; }

        #endregion

        #region Methodes

        /// <summary>
        /// Get an instance for the layout
        /// </summary>
        /// <returns></returns>
        public static LayoutViewModel Get()
        {
            return new LayoutViewModel();
        }

        #endregion
    }
}

Sources/MyBlog/Controllers/AboutController.cs
using System.Web.Mvc;

namespace MyBlog.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ViewResult Index()
        {
            return View();
        }

        public  ViewResult PrivacyAndUsage()
        {
            return View();
        }

        public ViewResult Cookies()
        {
            return View();
        }
    }
}

Sources/MyBlog/Controllers/FeedController.cs
using MyBlog.Engine;
using MyLib.Web.Results;
using System.Web.Mvc;

namespace MyBlog.Controllers
{
    public class FeedController : Controller
    {
        public ActionResult Index()
        {
            return new FeedResult(FeedService.Get(), FeedResult.Type.Rss);
        }

        public ActionResult Atom()
        {
            return new FeedResult(FeedService.Get(), FeedResult.Type.Atom);
        }

        public ActionResult Rss()
        {
            return new FeedResult(FeedService.Get(), FeedResult.Type.Rss);
        }
    }
}

Sources/MyBlog/Controllers/MailController.cs
using MyBlog.Engine;
using MyBlog.Models;
using MyBlog.Strings;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace MyBlog.Controllers
{
    public class MailController : Controller
    {
        private const String SendedView = "_Sended";

        /// <summary>
        ///  get Fomr
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            // Create model
            Mail model;

            // Try to get user logged
            var user = UserService.Get();

            // If user is available initialize mail
            model = user == null
                ? new Mail()
                : new Mail
                {
                    SenderMail = user.Email,
                    SenderName = user.Name
                };

            return View(model);
        }

        //Send mail
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(Mail model)
        {
            if (ModelState.IsValid)
            {
                // Try to send mail
                if (await MailService.Send(
                    Settings.Current.AuthorMail,
                    Settings.Current.AuthorName,
                    model.Subject,
                    String.Format("<p>{0} - {1}</p><p>{2}</p>",
                        model.SenderMail,
                        model.SenderName,
                        model.Content.Replace(Environment.NewLine, "<br/>"))
                        ))
                {
                    // Mail sended
                    return View(SendedView);
                }
                else
                {
                    // eeror when trying to send mail
                    ModelState.AddModelError(String.Empty, Resources.MailSendError);
                    return View(model);
                }
            }
            return View(model);
        }
    }
}

Sources/MyBlog/Controllers/PostController.cs
using MyBlog.Engine;
using MyBlog.Engine.Data.Models;
using MyBlog.Strings;
using MyBlog.Models;
using MyLib.Web;
using MyLib.Web.Helpers;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace MyBlog.Controllers
{
    public class PostController : Controller
    {
        #region Declarations

        private const String IndexGetMoreView = "_IndexGetMore";
        private const String FilterView = "Filter";
        private const String FilterGetMoreView = "_FilterGetMore";
        private const String SearchGetMoreView = "_SearchGetMore";

        #endregion

        #region Posts

        /// <summary>
        /// Default Action (get posts) 
        /// </summary>
        /// <param name="offset"></param>
        /// <returns></returns>
        public ActionResult Index(Posts model)
        {
            // Initialize the model
            InitializePosts(model);
            return View(model);
        }

        public PartialViewResult IndexGetMore(Posts model)
        {
            // Initialize the model
            InitializePosts(model);
            return PartialView(IndexGetMoreView, model);
        }

        /// <summary>
        /// Initialize the model for posts
        /// </summary>
        /// <param name="model"></param>
        private static void InitializePosts(Posts model)
        {
            using (var db = new DataService())
            {
                // Get items
                model.Items = db.GetPosts(model.Page * Settings.Current.PostQuantityPerPage);

                // Get Counter to know if we have more items to load
                Int32 count = db.Countposts();
                model.Available = count;
                model.HaveMoreResults = count > (model.Page + 1) * Settings.Current.PostQuantityPerPage;

                // Update offset
                model.NextPage = model.Page + 1;
            }
        }

        #endregion

        #region Categories

        /// <summary>
        /// Filter post by category
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult Category(PostsFilter model)
        {
            // Filters have to share the id
            if (Int32.TryParse(model.Id, out int id))
            {
                using (var db = new DataService())
                {
                    // Title
                    model.Title = Resources.Category;

                    // Get name
                    model.SubTitle = db.GetCategoryName(id);
                    model.Description = String.Format(
                        Resources.CategoryDescription,
                        model.SubTitle);

                    // Initialize the data
                    InitializeCategorymodel(db, model, id);
                }
            }
            return View(FilterView, model);
        }

        /// <summary>
        /// Get more items when filter posts by category
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public PartialViewResult CategoryGetMore(PostsFilter model)
        {
            // Filters have to share the id
            if (Int32.TryParse(model.Id, out int id))
            {
                using (var db = new DataService())
                {
                    InitializeCategorymodel(db, model, id);
                }
            }
            return PartialView(FilterGetMoreView, model);
        }

        /// <summary>
        /// Add data on model used by category
        /// </summary>
        /// <param name="db"></param>
        /// <param name="model"></param>
        private static void InitializeCategorymodel(DataService db, PostsFilter model,Int32 id)
        {
            // Action
            model.Action = "Category";

            // Gets posts
            model.Items = db.GetPostsInCategory(id, model.Page * Settings.Current.PostQuantityPerSearch);

            // Have more
            Int32 count = db.CounPostsInCategory(id);
            model.Available = count;
            model.HaveMoreResults = count > (model.Page + 1) * Settings.Current.PostQuantityPerSearch;

            // Update page index
            model.NextPage = model.Page + 1;
        }

        #endregion

        #region Details

        /// <summary>
        /// Get detail of post
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(Int32 id)
        {
            using (var db = new DataService())
            {
                // Initialize mode lwith post from database
                Details model = new Details()
                {
                    Post = db.GetPostWithDetails(id)
                };
                // Post not found
                if (model.Post == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    // Get description
                    model.Description = WebpageHelper.GetMetaDescrition(model.Post.Summary);

                    // Get previous and next posts informations, to display prevous and next buttons
                    DateTime date = model.Post.DateCreatedGmt;

                    model.PreviousPost = db.GetPreviousPost(id, date);
                    model.NextPost = db.GetNextPost(id, date);

                    // Build comment model to allow user to comment this post
                    UserProfile user = UserService.Get(db);
                    if (user == null)
                    {
                        model.Comment = null;
                        model.CurrentUserSubscibed = false;
                    }
                    else
                    {
                        model.Comment = new Comment();
                        model.CurrentUserSubscibed = db.HasCurrentUserSubscibed(id, user.Id);
                    }
                }

                return View(model);
            }
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Comment(Details model)
        {
            if (ModelState.IsValid)
            {
                using (var db = new DataService())
                {
                    // User id
                    Int32 userId = UserService.Get()?.Id ?? 0;

                    // Create the comment
                    await db.AddComment(model.Comment.Text, userId, model.Post.Id);
                }
            }
            return RedirectToAction("Details", new { id = model.Post.Id });
        }

        [Authorize]
        [HttpPost]
        public PartialViewResult SubscribToCommentNotification(Int32 id, Boolean subscription)
        {
            Boolean model;
            using(var db = new DataService())
            {
                // User id
                Int32 userId = UserService.Get()?.Id ?? 0;

                // Subscrib or unsubscribe
                model = db.SubscribToCommentNotification(id, userId, subscription);
            }
            return PartialView("_SubscribToCommentNotification", model);
        }

        #endregion

        #region Archives

        /// <summary>
        /// Filter post by category
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult Archive(PostsFilter model)
        {
            ArchiveId id = new ArchiveId(model.Id);
            using (var db = new DataService())
            {
                // Title
                model.Title = Resources.Archives;

                // Get name
                model.SubTitle = id.ToString();
                model.Description = String.Format(
                    Resources.ArchivesDescription,
                    model.SubTitle);

                // Initialize the data
                InitializeArchiveModel(db, model,id);
            }
            return View(FilterView, model);
        }

        /// <summary>
        /// Get more items when filter posts by category
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public PartialViewResult ArchiveGetMore(PostsFilter model)
        {
            ArchiveId id = new ArchiveId(model.Id);
            using (var db = new DataService())
            {
                InitializeArchiveModel(db, model, id);
            }
            return PartialView(FilterGetMoreView, model);
        }

        private static void InitializeArchiveModel(DataService db, PostsFilter model, ArchiveId id)
        {
            // Archive
            model.Action = "Archive";

            // Gets posts
            model.Items = db.GetPostsInArchive(id, model.Page * Settings.Current.PostQuantityPerSearch);

            // Have more
            Int32 count = db.CounPostsInArchive(id);
            model.Available = count;
            model.HaveMoreResults = count > (model.Page + 1) * Settings.Current.PostQuantityPerSearch;

            // Update page index
            model.NextPage = model.Page + 1;
        }

        #endregion

        #region Search

        /// <summary>
        /// Filter post by category
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult Search(SearchFilter model)
        {
            using (var db = new DataService())
            {
                // Title
                model.Title = Resources.Search;

                // Get name
                model.SubTitle = model.Query;
                model.Description = String.Format(
                    Resources.SearchDescription,
                    model.SubTitle);

                // Initialize the data
                InitializeSearchModel(db, model);
            }
            return View(model);
        }

        /// <summary>
        /// Get more items when filter posts by category
        /// </summary>
        /// <param name="model"></param>

Sources/MyBlog/Views/Shared/_Layout.cshtml
@{var model = LayoutViewModel.Get();}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no" />
    <meta name="description" content="@(ViewBag.Description ?? "[Your default description...]")">
    <meta name="robots" content="index" />
    <title>@(ViewBag.Title ?? Settings.Current.Title)</title>
    <link rel="icon" href="~/favicon.ico" type="image/x-icon" />
    <link rel="alternate" title="@Settings.Current.Title - RSS" type="application/rss+xml" href="@Url.Action("Rss","Feed")" />
    <link rel="alternate" title="@Settings.Current.Title - Atom" type="application/atom+xml" href="@Url.Action("Atom","Feed")" />
    <link rel="edituri" type="application/rsd+xml" href="/Content/rsd.xml" />
    <link rel="wlwmanifest" type="application/wlwmanifest+xml" href="/Content/wlwmanifest.xml" />
    @Styles.Render("~/Content/Layout")
    <link rel="stylesheet" href="@(model.UserSettings.LayoutContentUrl)" id="LayoutStylesheet" />
    @RenderSection("head", false)
    @if (IsSectionDefined("ldjson"))
    {
        @RenderSection("ldjson")
    }
    else
    {
        @Html.Partial("_OrganisationLdJson")
    }
</head>
<body class="bigheader">
    <div id="skiptocontent"><a href="#maincontent">Skip to main content <span aria-hidden="true">&rarr;</span></a></div>
    <header class="fixed-top">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/">
                    <div>
                        <img src="~/Content/Images/logo.png" alt="@Settings.Current.Title" aria-hidden="true" />
                        <h1>
                            @Settings.Current.Title
                            <small>@Settings.Current.SubTitle</small>
                        </h1>
                    </div>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="@Resources.ToggleNavigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarcollapse">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <button type="button" class="nav-link-button" onclick="PostAndDisplay('@WebUtility.HtmlEncode(Resources.AccessibilityFullTitle)','@Url.Action("_Accessibility","UserSettings")',null)">
                                <span class="sr-only">@Resources.AccessibilityFullTitle</span>
                                <span aria-hidden="true"><i class="fab fa-accessible-icon"></i> @Resources.Accessibility</span>
                            </button>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i aria-hidden="true" class="fa fa-tags"></i> @Resources.Categories</a>
                            <div class="dropdown-menu">
                                @foreach (var category in model.Categories)
                                {
                                    <a class="dropdown-item d-flex justify-content-between align-items-center" href="@Url.Action("Category", "Post", new { Id = category.Id })">@category.Name <span class="badge badge-pill badge-primary">@category.Count</span></a>
                                }
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-rss" aria-hidden="true"></i> @Resources.Feeds</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="@Url.Action("Atom","Feed")" type="application/atom+xml"><i class="fa fa-rss" aria-hidden="true"></i> @Resources.FeedAtom</a>
                                <a class="dropdown-item" href="@Url.Action("Rss","Feed")" type="application/rss+xml"><i class="fa fa-rss" aria-hidden="true"></i> @Resources.FeedRss</a>
                            </div>
                        </li>
                        <li>
                            <a class="nav-link" href="@Url.Action("Index","Mail")"><i class="fa fa-envelope"></i> @Resources.Mail</a>
                        </li>
                        @if (model.User == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link login" href="#"><i class="fa fa-sign-in-alt"></i> @Resources.LogInOrSignUp</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-circle" aria-hidden="true"></i> @(model.User.Name)</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="@Url.Action("Edit","Account")"><i class="far fa-id-card" aria-hidden="true"></i> @Resources.EditAccount</a>
                                    <a class="dropdown-item" href="@Url.Action("Logout", "Account")"><i class="fas fa-sign-out-alt" aria-hidden="true"></i> @Resources.Logout</a>
                                </div>
                            </li>
                        }
                    </ul>
                    @using (Html.BeginForm("Search", "Post", FormMethod.Get, new { @class = "form-inline my-2 my-lg-0", role = "search" }))
                    {
                        <div class="input-group">
                            <input type="text" class="form-control" aria-label="@Resources.Search" placeholder="@Resources.Search" id="query" name="query">
                            <span class="input-group-append">
                                <button type="submit" class="btn">
                                    <span class="fa fa-search"></span>
                                </button>
                            </span>
                        </div>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container" id="maincontent">
        <div class="row">
            <main class="col-lg-9">
                @RenderBody()
            </main>
            <aside class="col-lg-3">
                @using (Html.BeginPanel("<i class=\"fa fa-id-badge\" aria-hidden=\"true\"></i> " + Settings.Current.AuthorName, "me"))
                {
                    <div class="row">
                        <div class="col-lg-12 col-3">
                            <img class="img-fluid mx-auto d-block rounded-circle" src="~/Content/Images/me.png" alt="@Settings.Current.AuthorName" />
                        </div>
                        <div class="col-lg-12 col-9">
                            @Html.Raw("<center>[Your bio, ... etc ...]</center>")<br />
                            <a class="float-right" href="@Url.Action("Index","About")"><i class="fas fa-info"></i> @Resources.About</a>
                        </div>
                    </div>
                }
                @using (Html.BeginPanel("<i class=\"fa fa-tags\" aria-hidden=\"true\"></i> " + Resources.Categories, false))
                {
                    <div class="list-group list-group-wrap">
                        @foreach (var item in model.Categories)
                        {
                            <a class="list-group-item list-group-item-action col-12 col-sm-6 col-md-4 col-lg-12 d-flex justify-content-between align-items-center" href="@Url.Action("Category", "Post", new { Id = item.Id })">@item.Name <span class="badge badge-pill badge-primary">@item.Count</span></a>
                        }
                    </div>
                }
                @using (Html.BeginPanel("", "links"))
                {
                    <a href="https://twitter.com/[YourName]" target="_blank" class="btn btn-block btn-social btn-twitter">
                        <i class="fab fa-twitter"></i> Twitter
                    </a>
                    <a href="https://www.linkedin.com/in/[YourName]" target="_blank" class="btn btn-block btn-social btn-linkedin">
                        <i class="fab fa-linkedin-in"></i> LinkedIn
                    </a>
                    <a href="https://www.viadeo.com/fr/profile/[YourName]" target="_blank" class="btn btn-block btn-social btn-viadeo">
                        <i class="fab fa-viadeo"></i> Viadéo
                    </a>
                }
                @using (Html.BeginPanel("<i class='fa fa-calendar'></i> " + Resources.Archives, false))
                {
                    <div class="list-group list-group-wrap">
                        @foreach (var item in model.Archives)
                        {
                            <a class="list-group-item  list-group-item-action col-6 col-sm-3 col-lg-12 d-flex justify-content-between align-items-center" href="@Url.Action("Archive", "Post", new { Id = item.Id.Id })">@item.Title <span class="badge badge-pill badge-primary">@item.Count</span></a>
                        }
                    </div>
                }
            </aside>
        </div>
    </div>
    <footer>
        <div class="container d-flex flex-column">
            <div class="d-flex justify-content-center justify-content-md-start">
                <i class="fas fa-lightbulb" aria-hidden="true"></i> @Resources.Disclamer
            </div>
            <div class="d-flex flex-column justify-content-center flex-md-row justify-content-md-between">
                <ul class="list-unstyled d-flex flex-column  align-items-center align-items-md-start">
                    <li>
                        <a href="@Url.Action("Index","About")"><i class="fas fa-info" aria-hidden="true"></i> @Resources.About</a>
                    </li>
                    <li>
                        <a href="@Url.Action("PrivacyAndUsage","About")"><i class="fas fa-user-secret" aria-hidden="true"></i> @Resources.PrivacyPolicy</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Cookies","About")"><i class="fas fa-cookie-bite" aria-hidden="true"></i> @Resources.CookiesPolityTitle</a>
                    </li>
                </ul>
                <ul class="list-unstyled  d-flex  flex-column  align-items-center align-items-md-start">
                    <li><i class="fas fa-code" aria-hidden="true"></i> @(model.Version)</li>
                    <li><i class="fas fa-cloud" aria-hidden="true"></i> @(Resources.HostedOnAzure)</li>
                </ul>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/Scripts/Default")
    @if (!model.UserSettings.CookiesConcentClosed)
    {
        <div class="alert alert-info fade show footeralert" id="cookieConcent">
            <div class="container">
                <a href="#" class="close" aria-label="close"><span aria-hidden="true">&times;</span></a>
                <h2><i class="fas fa-cookie-bite"></i> @Resources.CookiesConcentTitle <small>@Html.ActionLink(Resources.CookiesPolityTitle, "Cookies", "About", null, new { @class = "alert-link" })</small></h2>
                @Resources.CookiesConcentContent
            </div>
        </div>
        <script>
            $(function () {
                setTimeout(function () { $("#cookieConcent").alert("close"); }, 10000);
                $("#cookieConcent .close").click(function () {
                    $.post("@Url.Action("CookiesConcentClosed", "UserSettings")", function () { $("#cookieConcent").alert("close"); })
                });
            });
        </script>
    }
    <script async src="@Scripts.Url("~/Scripts/Layout")"></script>
    @RenderSection("scripts", false)
</body>
</html>

Sources/MyBlog/Views/Shared/_OrganisationLdJson.cshtml
<script type="application/ld+json">
    {
    "@@context": "http://schema.org",
    "@@type": "Organization",
    "name": "@Settings.Current.AuthorName",
    "url": "@Settings.Current.Url",
    "logo": "@Settings.Current.Url/Content/Images/logo.png",
    "sameAs": [
    "https://twitter.com/JeremyJeanson",
    "https://www.linkedin.com/in/jeremyjeanson",
    "https://plus.google.com/106963170149599001962"
    ]
    }
</script>